language: node_js
node_js:
  - "5"
before_install:
  - 'gem update --system'
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
install: npm install
before_script: grunt build
