language: node_js
node_js:
  - stable

before_script:
  - 'gem update --system'
  - 'gem install sass'
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

cache:
  directories:
    - node_modules
